version: '2.1'
services:
  nocodb:
    env_file:
      - ../../../../.env.secrets
    depends_on:
      root_db:
        condition: service_healthy
    environment:
      NC_DB: ${NC_DB}
      NC_ADMIN_EMAIL: ${NC_ADMIN_EMAIL}
      NC_ADMIN_PASSWORD: ${NC_ADMIN_PASSWORD}
      DB_QUERY_LIMIT_DEFAULT: ${DB_QUERY_LIMIT_DEFAULT}
      DB_QUERY_LIMIT_GROUP_BY_GROUP: ${DB_QUERY_LIMIT_GROUP_BY_GROUP}
      DB_QUERY_LIMIT_GROUP_BY_RECORD: ${DB_QUERY_LIMIT_GROUP_BY_RECORD}
      DB_QUERY_LIMIT_MAX: ${DB_QUERY_LIMIT_MAX}
    image: "nocodb/nocodb:latest"
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "nc_data:/usr/app/data"

  root_db:
    env_file:
      - ../../../../.env.secrets
    environment:
      POSTGRES_DB: root_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      PGPORT: "5433"
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
volumes:
  db_data: {}
  nc_data: {}
